FROM python:3.7


# HippMapp3r 설치
RUN pip install hippmapp3r

WORKDIR /app

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

# 실행 명령: FastAPI가 docker exec로 호출할 것

ENTRYPOINT ["./entrypoint.sh"]
